require "core.options"
require "core.keymaps"
require "core.plugins"
require "core.nvim-tree"
require "aesthetics.theme"
require "aesthetics.generic"
require "codeRelated.toggle-term"
require "codeRelated.cmp"
require "codeRelated.comment"
require "codeRelated.lsp"
require "codeRelated.treesitter"

